from localisation.translations import (
    BIRTHDAY,
    FATHERSDAY,
    HAPPYFATHERSDAY,
    HAPPYMOTHERSDAY,
    MOTHERSDAY,
    THANKYOU,
    FORMALNAME,
    DESCRIPTION,
    SUPPORTEDPLATFORM,
)
