version: 2.1
jobs:
  build-ios:
    macos:
      xcode: "14.0.0"
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler -v 2.4.22
      - run:
          name: Install Dependencies
          command: |
            cd path/to/your/project # Ensure this points to the directory containing your Gemfile
            bundle install
      - run:
          name: Run Fastlane
          command: bundle exec fastlane ios build
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-ios